name: Publish Libtorch Release

# Trigger the workflow on tag creation
on:
  push:
    tags:
      - "v*"  # Trigger on version tags (e.g., v1.0.0)

jobs:
  download-compress-upload:
    runs-on: ubuntu-latest
    environment: Actions Release

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      # Step 2: Set up RAR utility
      - name: Install rar
        run: sudo apt-get install rar unrar -y

      # Step 3: Extract LibTorch version from tag
      - name: Extract LibTorch version
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          LIBTORCH_VERSION=$(echo $TAG_NAME | sed -n 's/.*+libtorch\([0-9.]*\).*/\1/p')
          echo "LIBTORCH_VERSION=$LIBTORCH_VERSION" >> $GITHUB_ENV

      # Step 4: Download the LibTorch CPU zip file
      - name: Download the LibTorch CPU distribution
        run: |
          LIBTORCH_CPU_URL=https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-${LIBTORCH_VERSION}%2Bcpu.zip
          curl -L -o libtorch_cpu.zip $LIBTORCH_CPU_URL

      # Step 5: Download the LibTorch GPU (CUDA) zip file
      - name: Download the LibTorch GPU (CUDA 12.1) distribution
        run: |
          LIBTORCH_GPU_URL=https://download.pytorch.org/libtorch/cu121/libtorch-win-shared-with-deps-${LIBTORCH_VERSION}%2Bcu121.zip
          curl -L -o libtorch_gpu.zip $LIBTORCH_GPU_URL

      # Step 6: Unzip the LibTorch CPU zip file
      - name: Unzip LibTorch CPU
        run: unzip libtorch_cpu.zip -d libtorch_cpu

      # Step 7: Unzip the LibTorch GPU zip file
      - name: Unzip LibTorch GPU
        run: unzip libtorch_gpu.zip -d libtorch_gpu

      # Step 8: Set execute permissions for the modify_headers.sh script
      - name: Set execute permissions for modify_headers.sh
        run: chmod +x ./Setup/modify_headers.sh

      # Step 10: Run script to make required changes to LibTorch CPU headers
      - name: Make changes to LibTorch CPU headers
        run: |
          chmod +x Setup/modify_headers.sh
          LIBTORCH_ROOT_CPU=libtorch_cpu/libtorch
          ./Setup/modify_headers.sh $LIBTORCH_ROOT_CPU

      # Step 11: Run script to make required changes to LibTorch GPU headers
      - name: Make changes to LibTorch GPU headers
        run: |
          LIBTORCH_ROOT_GPU=libtorch_gpu/libtorch
          ./Setup/modify_headers.sh $LIBTORCH_ROOT_GPU

      # Step 12: Compress the unzipped CPU folder using RAR
      - name: Compress LibTorch CPU with RAR
        run: rar a -r libtorch_cpu.rar libtorch_cpu

      # Step 13: Compress the unzipped GPU folder using RAR
      - name: Compress LibTorch GPU with RAR
        run: rar a -r libtorch_gpu.rar libtorch_gpu

      # Step 14: Generate a GitHub App token
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Step 15: Create a release and upload the RAR files as assets
      - name: Upload libtorch_cpu.rar and libtorch_gpu.rar to the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libtorch_cpu.rar
            libtorch_gpu.rar
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
